dist: xenial
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk/"
    - "node_modules"
services:
  - postgresql
addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - GOOGLE_APPLICATION_CREDENTIALS=service-account-travis-ci.json
    - GOOGLE_CLOUD_PROJECT=august-strata-281417
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account-travis-ci.json.enc -out service-account-travis-ci.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud version
  - gcloud auth activate-service-account --key-file service-account-travis-ci.json
install:
  - gcloud config set project $GOOGLE_CLOUD_PROJECT
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - bin/yarn
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - bin/rails db:prepare
script:
  - bundle exec rspec
before_deploy:
  - openssl aes-256-cbc -K $encrypted_8ad82cc635a3_key -iv $encrypted_8ad82cc635a3_iv -in config/master.key.enc -out config/master.key -d
  - RAILS_ENV=production bin/rails assets:precompile
  - bundle exec rake appengine:exec -- bin/rails db:prepare
deploy:
  provider: script
  script: gcloud -q app deploy app.yaml --promote
  skip_cleanup: true
  on:
    branch: master
