runtime: ruby25
entrypoint: bundle exec foreman start
instance_class: F2
env_variables:
  BASE_URL: https://studio.bindery.app
  COMPUTE_COMPOSITOR_TEMPLATE: compositor
  COMPUTE_ZONE: europe-west1-b
  DATABASE_HOST: /cloudsql/august-strata-281417:europe-west1:shampoo-abruptly-evaporate
  DATABASE_NAME: studio_production
  DATABASE_USERNAME: postgres
  DEPLOYED_BASE_URL: https://go.bindery.app
  GOOGLE_CLOUD_PROJECT: august-strata-281417
  PUBSUB_CLEANER_TOPIC: cleaner-topic
  RAILS_ENV: production
  SMTP_ADDRESS: smtp.eu.mailgun.org
  SMTP_FROM: noreply@bindery.app
  SMTP_PORT: 587
  SMTP_USERNAME: postmaster@mg.bindery.app
