version: "3.8"
services:
  db:
    image: "postgres:12.3"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  test:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
      - selenium
    volumes:
      - .:/app
      - /app/node_modules
    command: bin/spring server
    environment:
      TEST_APP_HOST: test
      TEST_APP_PORT: 3001
      SELENIUM_HOST: selenium
      RAILS_ENV: test
