version: "3.8"
services:
  db:
    image: "postgres:12.3"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: service-account-local.json
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  test:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
      - selenium
    volumes:
      - .:/app
      - /app/node_modules
    command: bin/spring server
    environment:
      COMPUTE_INSTANCE_TEMPLATE: my-instance-template
      COMPUTE_PROJECT: my-project
      COMPUTE_ZONE: my-zone
      GOOGLE_APPLICATION_CREDENTIALS: service-account-local.json
      RAILS_ENV: test
      SELENIUM_HOST: selenium
      TEST_APP_HOST: test
      TEST_APP_PORT: 3001
